# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BullyingDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection
  platform :ios, '12.2'
  pod 'Alamofire', '~> 5.0.0-rc.3'

end

target 'BullyingDetection WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection WatchKit App
  platform :watchos, '5.2'

end

target 'BullyingDetection WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection WatchKit Extension
  platform :watchos, '5.2'
  pod 'Alamofire', '~> 5.0.0-rc.3'

end
