# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BullyingDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection
  pod 'Alamofire', '~> 5.1'

end

target 'BullyingDetection WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection WatchKit App

end

target 'BullyingDetection WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullyingDetection WatchKit Extension
  pod 'Alamofire', '~> 5.1'

end
